spring.application.name=PublicKeyInfrastructure
server.port=8080

jwt.secret=RiVqAcxJZN639JBeZaTp6mnomOKf8Sdpe9O0tdvjrAtBPnpDjA3F5lhXWQ5Sh4u6WfJNYvoxdTX7gHCUwNrzyAnS
jwt.expiration.ms=3600000

#Spring DataSource drajver koji će se koristiti za komunikaciju aplikacije sa bazom
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.platform=postgres
#podrazumevani port za postgre je 5432
#jpa mora da bude kreirana prethodno u bazi
#spring.datasource.url=jdbc:postgresql://localhost:5432/IBDatabase
spring.datasource.url=jdbc:postgresql://localhost:5433/IBDatabase

#Navodi se URL do baze koja je pokrenuta u lokalu na podrazumevanom portu 5432 i na serveru je kreirana šema baze pod nazivom "jpa"
#https://www.pgadmin.org/docs/pgadmin4/4.14/schema_dialog.html (ako koristimo Hibernate za kreiranje tabela, SQL deo sa linka nije potreban)


#Navode se kredencijali za konekciju na server baze
spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.password=eventdb
#Umesto da sami pišemo SQL skriptu za kreiranje tabela u bazi, Hibernate kreira tabele na osnovu anotacija @Entity i kada aplikacija zavrsi sa radom dropuje ih (create-drop)
#https://www.baeldung.com/spring-boot-data-sql-and-schema-sql
#Ako želimo sami da kreiramo skriptu za kreiranje tabela potrebno je u src/main/resources folderu kreirati i popuniti fajl pod nazivom schema.sql koji će Spring Boot automatski pokrenuti pri pokretanju aplikacije
spring.jpa.hibernate.ddl-auto = validate

#Hibernate SQL upiti se ispisuju na IDE konzoli
spring.jpa.show-sql = false

#formatira ispis SQL upita koje Hibernate pravi ka bazi na IDE konzoli
spring.jpa.properties.hibernate.format_sql=false

#da bi se skripta pokrenula i popunila bazu podacima, potrebno je unijeti ove dvije linije
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never

#https://stackoverflow.com/questions/43905119/postgres-error-method-org-postgresql-jdbc-pgconnection-createclob-is-not-imple
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#Hibernate optimizacija SQL upita za Postgres bazu
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

#https://vladmihalcea.com/the-open-session-in-view-anti-pattern/
spring.jpa.open-in-view=false

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mexameksic123@gmail.com
spring.mail.password=bnbq gsei bodn jdqw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.debug=true

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=ibprojekat
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=PublicKeyInfrastructureApp